### ISSUE TITLE
Убрать говнокод

### ISSUE THREAD

**Issue by OctoNezd** [evgfilim1/itcoin_bot#2]

**Comment by evgfilim1** [comment]
@OctoNezd Бот находится на стадии тестирования, поэтому, этот вариант кода не будет совпадать с тем, что в релизе

**Comment by OctoNezd** [comment]
@evgfilim1 все вы так говорите

**Comment by OctoNezd** [comment]
потом евгените друг друга

**Comment by lamppcat** [comment]
@OctoNezd а потом продакшеном кормят детей без зубов
